import Head from 'next/head'
import { useSession } from 'next-auth/react'
import Navbar from '@/components/Navbar'
import { useEffect, useState } from 'react'
import Searchartist from '@/components/Searchartist'

export default function artist() {
  const { data: session }= useSession()
  console.log({ session })
  const [query, setQuery] = useState('')
  const [tracks, setTracks] = useState([])
  const [data, setdata] = useState()

 




  return (
    <div className="body">
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

        <Navbar/>
        <main > 
          <div className='artist-body' >
             Lets search some Artist
            
          </div> 
          
          <Searchartist/>
        </main>
        
    </div>
  )
}
